// Mabinogi Life Tool - shared game data
// Catalog data and recommendation metadata live here; app.js owns UI/state logic.
const APP_DATA_SCHEMA_VERSION = 2;
const DATA_VERSION = 3;
const PRIORITY_LABEL = {S_PLUS:'S+',S:'S',A:'A',B:'B'};
const TOWN_ORDER = ['提爾克那','杜加德走廊','杜巴頓','庫漢'];

const materials = {
  gearPart:{name:'分解的裝備零件',source:'分解／交換'},
  ore:{name:'礦石',source:'採礦'},
  ironOre:{name:'鐵礦石',source:'採礦／交換'},
  coal:{name:'煤炭',source:'採礦／交換'},
  steelIngot:{name:'鋼錠',source:'加工'},
  alloy:{name:'合金鋼錠',source:'交換／加工'},
  petFood:{name:'寵物飼料',source:'商店／製作'},
  highWool:{name:'高級羊毛',source:'交換／加工'},
  egg:{name:'雞蛋',source:'採集'},
  lavender:{name:'薰衣草花',source:'採集'},
  alchemyShard:{name:'煉金術碎屑',source:'交換'},
  flour:{name:'麵粉',source:'加工／交換'},
  mayoMeat:{name:'美乃滋炒肉',source:'料理'},
  critPotion:{name:'暴擊秘藥',source:'製作／交換'},
  appleJuice:{name:'蘋果汁',source:'料理'},
  catalystHi:{name:'高級鍊金術再燃燒催化劑',source:'交換'},
  catalystRare:{name:'稀有鍊金術再燃燒催化劑',source:'交換'},
  wholeWheatBread:{name:'凱琳特製全麥麵包',source:'交換'},
  holyWater:{name:'聖水',source:'交換'},
  milk:{name:'牛奶',source:'採集／商店'},
  spiderWeb:{name:'蜘蛛網',source:'採集'},
  wool:{name:'羊毛',source:'採集'},
  softWoolPillow:{name:'麥爾坎的鬆軟羊毛枕頭',source:'交換'},
  blankScore:{name:'空白樂譜',source:'交換'},
  campfireSet:{name:'專業營火套組',source:'製作'},
  mimiMushroom:{name:'咪咪蘑菇',source:'商店／採集'},
  fourLeaf:{name:'四葉草',source:'商店／交換'},
  log:{name:'原木',source:'伐木'},
  rawHide:{name:'生皮',source:'採集／交換'},
  highHide:{name:'高級生皮',source:'商店／採集／交換'},
  highHidePlus:{name:'高級生皮+',source:'商店／採集'},
  highLog:{name:'高級原木',source:'伐木／交換'},
  resin:{name:'樹液',source:'交換'},
  steamedClam:{name:'蒸蛤蜊',source:'料理'},
  musicBox:{name:'特蕾西原木音樂盒',source:'交換'},
  leather:{name:'皮革',source:'交換／加工'},
  highLeather:{name:'高級皮革',source:'加工'},
  tanninPowder:{name:'單寧粉末',source:'交換'},
  stirVeg:{name:'炒蔬菜',source:'料理'},
  highWood:{name:'高級木材',source:'交換／加工'},
  larva:{name:'幼蟲',source:'採集'},
  fabricPlus:{name:'布料+',source:'交換／加工'},
  perfectBandage:{name:'完美繃帶',source:'製作'},
  highSilk:{name:'高級絲綢',source:'加工'},
  dyeBase:{name:'染色劑基底',source:'交換'},
  ghostFirefly:{name:'幽靈螢火蟲',source:'採蟲'},
  carvedOlivineS:{name:'雕琢橄欖石S',source:'加工'},
  trueLoveFish:{name:'真愛魚',source:'釣魚'},
  shadowGhostFish:{name:'暗影幽靈魚',source:'釣魚'},
  fireGrenade:{name:'火焰魔法榴彈',source:'交換'},
  lightningGrenade:{name:'閃電魔法榴彈',source:'交換'},
  windGrenade:{name:'風魔法榴彈',source:'交換'},
  acidGrenade:{name:'酸蝕魔法榴彈',source:'交換'},
  heartCoin:{name:'愛心幣',source:'交換'},
  appleSouffle:{name:'蘋果舒芙蕾',source:'料理'},
  milkPorkStew:{name:'牛奶燉豬肉',source:'料理'},
  cream:{name:'鮮奶油',source:'料理／加工'},
  glenisCake:{name:'格莉娜手工蛋糕',source:'交換'},
  glenisAppleTea:{name:'格莉娜的蘋果奶茶',source:'交換'},
  lifeStone:{name:'生命的魔力石',source:'交換'},
  cleanSpore:{name:'淨淨蘑菇孢子',source:'採集'},
  healthDrink:{name:'健康飲料',source:'交換'},
  garlicOlivePasta:{name:'蒜香橄欖油義大利麵',source:'料理'},
  ruinStone:{name:'廢墟魔力石',source:'交換／副本'},
  valleyStone:{name:'峽谷魔力石',source:'交換／副本'},
  lanternAngler:{name:'燈籠鮟鱇',source:'釣魚'},
  specialSteel:{name:'特殊鋼錠',source:'交換／加工'},
  silverAlloy:{name:'銀合金錠',source:'交換'},
  whiteCopperOre:{name:'白銅礦石',source:'採礦'},
  copperOre:{name:'銅礦石',source:'採礦／交換'},
  heatBandage:{name:'耐熱繃帶',source:'製作'},
  poisonSac:{name:'毒囊',source:'採集'},
  sunsetButterfly:{name:'夕陽蝴蝶',source:'採蟲'},
  bpFoodProcess:{name:'食材加工設備設計圖(3級)',source:'交換'},
  bpMultiBench:{name:'多用途製作台設計圖(3級)',source:'交換'},
  bpWoodProcess:{name:'木材加工設備設計圖(3級)',source:'交換'},
  bpLeatherProcess:{name:'皮革加工設備設計圖(3級)',source:'交換'},
  bpFabricProcess:{name:'布料加工設備設計圖(3級)',source:'交換'},
  bpArmorBench:{name:'防具製作台設計圖(3級)',source:'交換'},
  bpFoodBench:{name:'食物製作台設計圖(3級)',source:'交換'},
  bpMedicineProcess:{name:'藥品加工設備設計圖(3級)',source:'交換'},
  bpMedicineBench:{name:'藥品製作台設計圖(3級)',source:'交換'},
  bpMetalProcess:{name:'金屬加工設備設計圖(3級)',source:'交換'},
  bpWeaponBench:{name:'武器製作台設計圖(3級)',source:'交換'},
  asparagus:{name:'蘆筍',source:'商店'},pepper:{name:'胡椒',source:'商店'},salt:{name:'鹽',source:'商店'},lemon:{name:'檸檬',source:'商店'},tomato:{name:'番茄',source:'商店'},garlic:{name:'大蒜',source:'商店'},peas:{name:'豌豆',source:'商店'},meat:{name:'肉',source:'商店'},oil:{name:'食用油',source:'商店'},apple:{name:'蘋果',source:'商店'},sugar:{name:'糖',source:'商店'},cabbage:{name:'高麗菜',source:'商店'},shellfish:{name:'貝類',source:'商店'},ice:{name:'冰',source:'商店'},strawberry:{name:'草莓',source:'商店'},
  bloodHerb:{name:'血紅藥草',source:'商店／採集'},arrowFlower:{name:'箭花',source:'商店／採集'},magicHerb:{name:'魔力藥草',source:'商店／採集'},gritHerb:{name:'毅力草',source:'商店／採集'},strongPowder:{name:'壯壯蘑菇粉末',source:'商店／加工'},strongJuice:{name:'壯壯蘑菇汁液',source:'商店／加工'},mimiJuice:{name:'咪咪蘑菇汁液',source:'商店／加工'},sproutJuice:{name:'新芽蘑菇汁液',source:'商店／加工'},hiddenFlower:{name:'躲躲花',source:'商店／採集'},hiddenPowder:{name:'躲躲花粉末',source:'商店／加工'},cleanMushroom:{name:'淨淨蘑菇',source:'商店／採集'},cleanJuice:{name:'淨淨蘑菇汁液',source:'商店／加工'},beetle:{name:'獨角仙',source:'商店／採蟲'},firefly:{name:'滴答螢火蟲',source:'商店／採蟲'},
  mackerel:{name:'鯖魚',source:'釣魚'},salmon:{name:'鮭魚',source:'釣魚'},mayo:{name:'美乃滋',source:'料理前置'},brihneCarp:{name:'布里赫內鯉魚',source:'釣魚'},silverCrucian:{name:'銀鯽',source:'釣魚'},potato:{name:'馬鈴薯',source:'採集'},rainbowTrout:{name:'彩虹鱒',source:'釣魚'},sweetfish:{name:'香魚',source:'釣魚'},onion:{name:'洋蔥',source:'採集／商店'},catfish:{name:'鯰魚',source:'釣魚'},coinBeetle:{name:'硬幣瓢蟲',source:'採蟲'}
};

const recipes = {
  mackerelSteak:{name:'鯖魚與鮭魚排',priority:'S_PLUS',outputQty:1,tier:1,ingredients:{mackerel:5,salmon:3,mayo:2,asparagus:4,salt:2,pepper:3}},
  meuniere:{name:'白肉魚穆尼耶爾',priority:'S',outputQty:1,tier:1,ingredients:{brihneCarp:5,silverCrucian:3,potato:5,flour:3,lemon:5,salt:3}},
  bouillabaisse:{name:'法式海鮮湯',priority:'S',outputQty:1,tier:1,ingredients:{rainbowTrout:4,sweetfish:4,tomato:6,shellfish:5,onion:2,garlic:4}},
  fishChips:{name:'鯰魚炸魚薯條',priority:'A',outputQty:1,tier:1,ingredients:{catfish:6,potato:6,flour:3,peas:4,lemon:2,salt:3}},
  critPotion:{name:'暴擊秘藥',priority:'S_PLUS',outputQty:3,tier:1,ingredients:{fourLeaf:10,mimiJuice:3,coinBeetle:6,alchemyShard:10}},
  advancedCrit:{name:'高級暴擊秘藥',priority:'S_PLUS',outputQty:3,tier:2,ingredients:{critPotion:9,cleanJuice:5,ruinStone:1,alchemyShard:20}}
};

const barterCatalog = [
  {id:'tir-deian-wool',town:'提爾克那',order:1,npc:'迪恩',type:'barter',priority:'A',input:'petFood',inputQty:1,output:'highWool',outputQty:4,limit:10,why:'用少量寵物飼料快速補高級羊毛；需要布料／羊毛加工時再換。'},
  {id:'tir-furgus-iron',town:'提爾克那',order:2,npc:'佛格斯',type:'barter',priority:'A',input:'gearPart',inputQty:1,output:'ironOre',outputQty:1,limit:10,why:'把分解零件轉成鐵礦石；缺鐵礦時才需要。'},
  {id:'tir-furgus-coal',town:'提爾克那',order:2,npc:'佛格斯',type:'barter',priority:'S',input:'gearPart',inputQty:1,output:'coal',outputQty:3,limit:10,recommendedCount:10,why:'煤炭是金屬加工常見瓶頸；垃圾裝備零件有餘量時交換效率高。'},
  {id:'tir-furgus-alloy',town:'提爾克那',order:2,npc:'佛格斯',type:'barter',priority:'S_PLUS',input:'steelIngot',inputQty:2,output:'alloy',outputQty:1,limit:4,recommendedCount:4,why:'合金鋼錠是高階金屬供應鏈的重要中間材料。'},
  {id:'tir-furgus-parts',town:'提爾克那',order:2,npc:'佛格斯',type:'barter',priority:'B',input:'ore',inputQty:100,output:'gearPart',outputQty:10,limit:1,why:'用大量一般礦石換分解零件；通常只在零件缺口明確時使用。'},
  {id:'tir-elisa-egg',town:'提爾克那',order:3,npc:'愛麗沙',type:'barter',priority:'S_PLUS',input:'egg',inputQty:10,output:'alchemyShard',outputQty:1,limit:1,recommendedCount:1,why:'煉金術碎屑是多種戰鬥秘藥的核心材料。'},
  {id:'tir-elisa-lav',town:'提爾克那',order:3,npc:'愛麗沙',type:'barter',priority:'S_PLUS',input:'lavender',inputQty:1,output:'alchemyShard',outputQty:1,limit:1,recommendedCount:1,why:'用少量採集物換核心碎屑，價值高。'},
  {id:'tir-elisa-flour-egg',town:'提爾克那',order:3,npc:'愛麗沙',type:'barter',priority:'B',input:'egg',inputQty:3,output:'flour',outputQty:1,limit:1,why:'臨時缺麵粉時可用雞蛋補；平常不必固定交換。'},
  {id:'tir-elisa-flour-lav',town:'提爾克那',order:3,npc:'愛麗沙',type:'barter',priority:'B',input:'lavender',inputQty:1,output:'flour',outputQty:1,limit:1,why:'另一條麵粉取得路線；有料理缺口時再使用。'},
  {id:'tir-reynard',town:'提爾克那',order:4,npc:'雷納德',type:'barter',priority:'S_PLUS',input:'mayoMeat',inputQty:2,output:'critPotion',outputQty:1,limit:1,recommendedCount:1,why:'直接取得戰鬥會用到的暴擊秘藥，也能降低高級暴擊秘藥的前置製作量。'},
  {id:'tir-lisa',town:'提爾克那',order:5,npc:'麗莎',type:'barter',priority:'S_PLUS',input:'appleJuice',inputQty:1,output:'catalystHi',outputQty:1,limit:1,recommendedCount:1,why:'用料理換高級再燃燒催化劑，長期累積價值高。'},
  {id:'tir-lisa-shard',town:'提爾克那',order:5,npc:'麗莎',type:'barter',priority:'S',input:'alchemyShard',inputQty:3,output:'catalystHi',outputQty:1,limit:1,recommendedCount:1,why:'可再補一顆高級催化劑；但會消耗煉金術碎屑，秘藥需求高時可自行跳過。'},
  {id:'tir-lisa-rare',town:'提爾克那',order:5,npc:'麗莎',type:'barter',priority:'S_PLUS',input:'catalystHi',inputQty:15,output:'catalystRare',outputQty:1,limit:1,why:'把累積的高級催化劑升成稀有催化劑；需有足夠庫存再換。'},
  {id:'tir-andeli-holy',town:'提爾克那',order:6,npc:'安黛莉',type:'barter',priority:'B',input:'wholeWheatBread',inputQty:1,output:'holyWater',outputQty:1,limit:1,why:'全麥麵包的後續交換之一，需要聖水時再做。'},
  {id:'tir-meven-holy',town:'提爾克那',order:7,npc:'梅文',type:'barter',priority:'B',input:'wholeWheatBread',inputQty:1,output:'holyWater',outputQty:1,limit:1,why:'全麥麵包的另一個聖水交換來源。'},
  {id:'tir-kailin-bread',town:'提爾克那',order:8,npc:'凱琳',type:'barter',priority:'A',input:'milk',inputQty:10,output:'wholeWheatBread',outputQty:3,limit:1,why:'可再拿給安黛莉／梅文換聖水，也能作為特定任務材料。'},
  {id:'tir-kailin-bp-food',town:'提爾克那',order:8,npc:'凱琳',type:'barter',priority:'B',input:'flour',inputQty:10,output:'bpFoodProcess',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'tir-malcolm-pillow',town:'提爾克那',order:9,npc:'麥爾坎',type:'barter',priority:'B',input:'spiderWeb',inputQty:5,output:'softWoolPillow',outputQty:1,limit:1,why:'收藏／特定用途交換品；不是固定每日必換。'},
  {id:'tir-malcolm-score',town:'提爾克那',order:9,npc:'麥爾坎',type:'barter',priority:'B',input:'wool',inputQty:50,output:'blankScore',outputQty:1,limit:1,why:'需要空白樂譜時再換。'},
  {id:'tir-malcolm-bp',town:'提爾克那',order:9,npc:'麥爾坎',type:'barter',priority:'B',input:'campfireSet',inputQty:1,output:'bpMultiBench',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'tir-dilys-clover',town:'提爾克那',order:10,npc:'迪莉絲',type:'barter',priority:'A',input:'mimiMushroom',inputQty:3,output:'fourLeaf',outputQty:1,limit:1,why:'四葉草可投入暴擊秘藥供應鏈；手上咪咪蘑菇有餘量時可換。'},
  {id:'dug-tracy-hide',town:'杜加德走廊',order:1,npc:'特蕾西',type:'barter',priority:'B',input:'log',inputQty:1,output:'rawHide',outputQty:1,limit:10,why:'原木換生皮；只在皮革加工缺生皮時需要。'},
  {id:'dug-tracy-highhide',town:'杜加德走廊',order:1,npc:'特蕾西',type:'barter',priority:'A',input:'log',inputQty:10,output:'highHide',outputQty:1,limit:10,why:'用大量原木換高級生皮；需要高階皮革材料時再做。'},
  {id:'dug-tracy-resin',town:'杜加德走廊',order:1,npc:'特蕾西',type:'barter',priority:'S',input:'highLog',inputQty:1,output:'resin',outputQty:4,limit:5,recommendedCount:5,why:'樹液是高階木材加工的重要瓶頸。'},
  {id:'dug-tracy-box',town:'杜加德走廊',order:1,npc:'特蕾西',type:'barter',priority:'A',input:'steamedClam',inputQty:2,output:'musicBox',outputQty:1,limit:1,recommendedCount:1,why:'音樂盒可帶到杜巴頓找瓦爾特換皮革，形成跨城供應鏈。'},
  {id:'dug-tracy-bp',town:'杜加德走廊',order:1,npc:'特蕾西',type:'barter',priority:'B',input:'larva',inputQty:5,output:'bpWoodProcess',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'dug-elven-tannin',town:'杜加德走廊',order:2,npc:'艾爾文',type:'barter',priority:'B',input:'rawHide',inputQty:5,output:'tanninPowder',outputQty:5,limit:10,why:'皮革加工材料；缺單寧粉末時才需要。'},
  {id:'dug-elven-highlog',town:'杜加德走廊',order:2,npc:'艾爾文',type:'barter',priority:'A',input:'highLeather',inputQty:1,output:'highLog',outputQty:1,limit:10,why:'把高級皮革轉成高級原木；可再銜接特蕾西換樹液。'},
  {id:'dug-elven-wood',town:'杜加德走廊',order:2,npc:'艾爾文',type:'barter',priority:'S',input:'stirVeg',inputQty:1,output:'highWood',outputQty:4,limit:2,recommendedCount:2,why:'用料理快速換高級木材，節省加工時間。'},
  {id:'dug-elven-bp',town:'杜加德走廊',order:2,npc:'艾爾文',type:'barter',priority:'B',input:'fabricPlus',inputQty:5,output:'bpLeatherProcess',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'dun-simon-fabric',town:'杜巴頓',order:1,npc:'西蒙',type:'barter',priority:'A',input:'perfectBandage',inputQty:100,output:'fabricPlus',outputQty:10,limit:10,why:'大量繃帶可換布料+；有布料加工需求時再換。'},
  {id:'dun-simon-dye',town:'杜巴頓',order:1,npc:'西蒙',type:'barter',priority:'A',input:'highSilk',inputQty:10,output:'dyeBase',outputQty:1,limit:1,why:'染色劑基底的交換來源。'},
  {id:'dun-simon-bp-fabric',town:'杜巴頓',order:1,npc:'西蒙',type:'barter',priority:'B',input:'ghostFirefly',inputQty:2,output:'bpFabricProcess',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'dun-simon-bp-armor',town:'杜巴頓',order:1,npc:'西蒙',type:'barter',priority:'B',input:'carvedOlivineS',inputQty:1,output:'bpArmorBench',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'dun-walter-leather',town:'杜巴頓',order:2,npc:'瓦爾特',type:'barter',priority:'A',input:'musicBox',inputQty:1,output:'leather',outputQty:6,limit:2,recommendedCount:1,why:'特蕾西原木音樂盒的後續交換；正常每日路線可用當天取得的 1 個音樂盒換 6 皮革。'},
  {id:'dun-walter-heart',town:'杜巴頓',order:2,npc:'瓦爾特',type:'barter',priority:'B',input:'trueLoveFish',inputQty:5,output:'heartCoin',outputQty:1,limit:2,why:'真愛魚換愛心幣；依活動／收藏需求決定。'},
  {id:'dun-walter-fire',town:'杜巴頓',order:2,npc:'瓦爾特',type:'barter',priority:'B',input:'shadowGhostFish',inputQty:5,output:'fireGrenade',outputQty:1,limit:3,why:'暗影幽靈魚可換火焰魔法榴彈。'},
  {id:'dun-walter-lightning',town:'杜巴頓',order:2,npc:'瓦爾特',type:'barter',priority:'B',input:'shadowGhostFish',inputQty:5,output:'lightningGrenade',outputQty:1,limit:3,why:'暗影幽靈魚可換閃電魔法榴彈。'},
  {id:'dun-walter-wind',town:'杜巴頓',order:2,npc:'瓦爾特',type:'barter',priority:'B',input:'shadowGhostFish',inputQty:5,output:'windGrenade',outputQty:1,limit:3,why:'暗影幽靈魚可換風魔法榴彈。'},
  {id:'dun-walter-acid',town:'杜巴頓',order:2,npc:'瓦爾特',type:'barter',priority:'B',input:'shadowGhostFish',inputQty:5,output:'acidGrenade',outputQty:1,limit:3,why:'暗影幽靈魚可換酸蝕魔法榴彈。'},
  {id:'dun-glenis-cake',town:'杜巴頓',order:3,npc:'格莉娜',type:'barter',priority:'A',input:'milkPorkStew',inputQty:1,output:'glenisCake',outputQty:1,limit:1,why:'格莉娜限定料理交換。'},
  {id:'dun-glenis-tea',town:'杜巴頓',order:3,npc:'格莉娜',type:'barter',priority:'A',input:'cream',inputQty:4,output:'glenisAppleTea',outputQty:1,limit:1,why:'格莉娜限定飲品交換。'},
  {id:'dun-glenis-bp',town:'杜巴頓',order:3,npc:'格莉娜',type:'barter',priority:'B',input:'appleSouffle',inputQty:1,output:'bpFoodBench',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'dun-manus-life',town:'杜巴頓',order:4,npc:'馬努斯',type:'barter',priority:'S_PLUS',input:'petFood',inputQty:10,output:'lifeStone',outputQty:1,limit:2,recommendedCount:2,why:'生命魔力石可作高階材料，也可到庫漢交換廢墟／峽谷魔力石。'},
  {id:'cobh-gilian-health',town:'庫漢',order:1,npc:'基利安',type:'barter',priority:'A',input:'cleanSpore',inputQty:5,output:'healthDrink',outputQty:1,limit:5,recommendedCount:3,why:'健康飲料可再交給康納換四葉草；推薦量 3 次剛好銜接康納每日上限。'},
  {id:'cobh-gilian-pasta',town:'庫漢',order:1,npc:'基利安',type:'barter',priority:'S',input:'garlicOlivePasta',inputQty:1,output:'fourLeaf',outputQty:8,limit:1,recommendedCount:1,why:'直接取得 8 個四葉草，可投入暴擊秘藥供應鏈。'},
  {id:'cobh-gilian-bp-process',town:'庫漢',order:1,npc:'基利安',type:'barter',priority:'B',input:'poisonSac',inputQty:3,output:'bpMedicineProcess',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'cobh-gilian-bp-bench',town:'庫漢',order:1,npc:'基利安',type:'barter',priority:'B',input:'sunsetButterfly',inputQty:2,output:'bpMedicineBench',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'cobh-connor-clover',town:'庫漢',order:2,npc:'康納',type:'barter',priority:'S',input:'healthDrink',inputQty:1,output:'fourLeaf',outputQty:3,limit:3,recommendedCount:3,why:'把基利安換到的健康飲料再轉成四葉草，是跨 NPC 供應鏈。'},
  {id:'cobh-connor-ruin',town:'庫漢',order:2,npc:'康納',type:'barter',priority:'A',input:'lifeStone',inputQty:1,output:'ruinStone',outputQty:1,limit:5,conditional:'production',why:'高級暴擊秘藥需要廢墟魔力石；只有生產缺口時才換，避免把生命魔力石全轉掉。'},
  {id:'cobh-connor-valley',town:'庫漢',order:2,npc:'康納',type:'barter',priority:'B',input:'lifeStone',inputQty:1,output:'valleyStone',outputQty:1,limit:10,why:'生命魔力石可轉峽谷魔力石；目前沒有明確生產目標時不建議固定兌換。'},
  {id:'cobh-connor-heart',town:'庫漢',order:2,npc:'康納',type:'barter',priority:'B',input:'lanternAngler',inputQty:1,output:'heartCoin',outputQty:1,limit:3,why:'燈籠鮟鱇換愛心幣；依活動／收藏需求使用。'},
  {id:'cobh-armis-silver',town:'庫漢',order:3,npc:'阿爾米斯',type:'barter',priority:'S_PLUS',input:'specialSteel',inputQty:2,output:'silverAlloy',outputQty:1,limit:1,recommendedCount:1,why:'銀合金錠是高階裝備與生活工具的長期戰略物資。'},
  {id:'cobh-armis-copper',town:'庫漢',order:3,npc:'阿爾米斯',type:'barter',priority:'B',input:'whiteCopperOre',inputQty:1,output:'copperOre',outputQty:10,limit:1,why:'白銅礦石可換大量銅礦石；有銅礦缺口時再做。'},
  {id:'cobh-armis-bp-metal',town:'庫漢',order:3,npc:'阿爾米斯',type:'barter',priority:'B',input:'coal',inputQty:20,output:'bpMetalProcess',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'},
  {id:'cobh-armis-bp-weapon',town:'庫漢',order:3,npc:'阿爾米斯',type:'barter',priority:'B',input:'heatBandage',inputQty:5,output:'bpWeaponBench',outputQty:1,limit:1,oneTime:true,why:'一次性設計圖；取得後標記永久完成即可。'}
];

const shopCatalog = [
  {id:'dun-glenna-asparagus',town:'杜巴頓',order:1,npc:'格莉娜',type:'shop',priority:'S_PLUS',output:'asparagus',price:10000,limit:null,why:'高級料理瓶頸食材；依生產目標補足。'},
  {id:'dun-glenna-pepper',town:'杜巴頓',order:1,npc:'格莉娜',type:'shop',priority:'S_PLUS',output:'pepper',price:2000,limit:null,why:'高級料理常用；依本週料理目標補足。'},
  {id:'dun-glenna-salt',town:'杜巴頓',order:1,npc:'格莉娜',type:'shop',priority:'S',output:'salt',price:1000,limit:null,why:'多種高級料理共同材料。'},
  {id:'dun-glenna-lemon',town:'杜巴頓',order:1,npc:'格莉娜',type:'shop',priority:'S',output:'lemon',price:3000,limit:null,why:'穆尼耶爾與炸魚薯條等高級料理材料。'},
  {id:'dun-glenna-tomato',town:'杜巴頓',order:1,npc:'格莉娜',type:'shop',priority:'S',output:'tomato',price:6800,limit:null,why:'法式海鮮湯核心材料。'},
  {id:'dun-glenna-garlic',town:'杜巴頓',order:1,npc:'格莉娜',type:'shop',priority:'S',output:'garlic',price:1200,limit:null,why:'法式海鮮湯等高級料理材料。'},
  {id:'dun-glenna-peas',town:'杜巴頓',order:1,npc:'格莉娜',type:'shop',priority:'S',output:'peas',price:10000,limit:null,why:'鯰魚炸魚薯條材料。'},
  {id:'dun-manus-blood',town:'杜巴頓',order:2,npc:'馬努斯',type:'shop',priority:'S',output:'bloodHerb',price:250,limit:30,why:'傷害減免／強打強化等戰鬥秘藥材料。'},
  {id:'dun-manus-arrow',town:'杜巴頓',order:2,npc:'馬努斯',type:'shop',priority:'A',output:'arrowFlower',price:400,limit:30,why:'移動速度等藥品路線材料。'},
  {id:'dun-manus-grit',town:'杜巴頓',order:2,npc:'馬努斯',type:'shop',priority:'S',output:'gritHerb',price:400,limit:30,why:'終極技類秘藥的重要藥草。'},
  {id:'dun-manus-mimi',town:'杜巴頓',order:2,npc:'馬努斯',type:'shop',priority:'S_PLUS',output:'mimiJuice',price:600,limit:30,why:'多種基礎戰鬥秘藥共用材料。'},
  {id:'dun-manus-sprout',town:'杜巴頓',order:2,npc:'馬努斯',type:'shop',priority:'A',output:'sproutJuice',price:400,limit:30,why:'多種高階藥品的加工材料。'},
  {id:'cobh-gilian-four',town:'庫漢',order:1,npc:'基利安',type:'shop',priority:'S_PLUS',output:'fourLeaf',price:750,limit:null,why:'暴擊秘藥供應鏈核心；依生產目標計算需求。'},
  {id:'cobh-gilian-cleanjuice',town:'庫漢',order:1,npc:'基利安',type:'shop',priority:'S_PLUS',output:'cleanJuice',price:750,limit:null,why:'高級暴擊等高階秘藥直接材料。'},
  {id:'cobh-gilian-clean',town:'庫漢',order:1,npc:'基利安',type:'shop',priority:'A',output:'cleanMushroom',price:600,limit:null,why:'可自行加工成汁液。'},
  {id:'cobh-gilian-hidden',town:'庫漢',order:1,npc:'基利安',type:'shop',priority:'B',output:'hiddenFlower',price:150,limit:30,why:'高階恢復／加工用途。'},
  {id:'cobh-gilian-hiddenpowder',town:'庫漢',order:1,npc:'基利安',type:'shop',priority:'B',output:'hiddenPowder',price:900,limit:30,why:'特殊加工路線材料。'},
  {id:'cobh-gilian-strongpowder',town:'庫漢',order:1,npc:'基利安',type:'shop',priority:'B',output:'strongPowder',price:600,limit:30,why:'特殊加工路線材料。'},
  {id:'cobh-connor-asparagus',town:'庫漢',order:2,npc:'康納',type:'shop',priority:'S_PLUS',output:'asparagus',price:10000,limit:null,why:'第二個蘆筍來源；只分配尚未滿足的缺口。'},
  {id:'cobh-connor-pepper',town:'庫漢',order:2,npc:'康納',type:'shop',priority:'S_PLUS',output:'pepper',price:2000,limit:null,why:'高級料理共同材料。'},
  {id:'cobh-connor-tomato',town:'庫漢',order:2,npc:'康納',type:'shop',priority:'S',output:'tomato',price:6800,limit:30,why:'法式海鮮湯材料。'},
  {id:'cobh-connor-peas',town:'庫漢',order:2,npc:'康納',type:'shop',priority:'S',output:'peas',price:10000,limit:30,why:'炸魚薯條材料。'},
  {id:'cobh-connor-beetle',town:'庫漢',order:2,npc:'康納',type:'shop',priority:'B',output:'beetle',price:500,limit:30,why:'減傷／強打類秘藥與採集定位。'},
  {id:'cobh-connor-firefly',town:'庫漢',order:2,npc:'康納',type:'shop',priority:'A',output:'firefly',price:400,limit:30,why:'移速類秘藥材料。'},
  {id:'cobh-connor-highhide',town:'庫漢',order:2,npc:'康納',type:'shop',priority:'A',output:'highHidePlus',price:600,limit:30,why:'高階皮革加工與製裝長期素材。'}
];

const tasks = [...barterCatalog, ...shopCatalog];